### ISSUE TITLE
New Image size preview

### ISSUE THREAD

**Issue by ApoorvaJ** [ApoorvaJ/Papaya#14]
Whenever an image is not open, I show the "New Image" options in the tool options bar, as shown in the image below.

![image](https://cloud.githubusercontent.com/assets/2312221/14537006/c50f36c8-0292-11e6-9b3b-abfd8c2b3b5b.png)

It would be great to have a checkbox called "Preview" right next to the Size input box. If checked, this would draw a quad with the actual size specified in the Size input box. This would help give the user a sense of how big the image will be, when created.

A good way to achieve this would be to draw a custom-shaded quad if the Preview checkbox is checked.

Here's a mockup of what that would look like (sans the Preview checkbox):

![untitled](https://cloud.githubusercontent.com/assets/2312221/14537509/e1f73554-0294-11e6-855b-b24ecfe45fca.png)

This is an intermediate-difficulty change. Have a look at how the color picker gradients are handled to understand how to implement this. Most code will be in `papaya_core.cpp`. Shader code and initialization is in `Core::Initialize()`. Color picker drawing is currently in the same file under the heading `// Color Picker Panel`.

If you do decide to take this up, even a rough implementation from you would be of help. I can take care of the polishing.

**Comment by ands** [comment]
This button does not show up for me in the version from the release page. Was it added after the release?

**Comment by ApoorvaJ** [comment]
Yes, it was added post-release.
