### ISSUE TITLE
Center the document on Window Resize

### ISSUE THREAD

**Issue by DeltaManiac** [ApoorvaJ/Papaya#17]
The opened document does not stay at the center on resize until a zoom Operation is performed.
Would be cool if it remained at the center on window resize too.

**Comment by ApoorvaJ** [comment]
Commented on pull request.

**Comment by ApoorvaJ** [comment]
Added this functionality myself based on your initial pull request. Closing issue.

See commits:
cf11071fda2699069a7fea3323354943a154a0ad
82eaabddf2e7b352ba287b0b80960b8ac9b6219b
