### ISSUE TITLE
Merge OSX Repo

### ISSUE THREAD

**Issue by DeltaManiac** [ApoorvaJ/Papaya#22]
Is there any plan to merge the OSX repo into the this one ?

**Comment by ApoorvaJ** [comment]
Nope. I don't own a Mac, and so can't ensure that building+running works successfully.

Also, currently most features can either be divided into platform features or application features. You can thus submit application pull requests here, and Mac pull requests in the Mac repository.

There's still a lot of work that needs to be done on just ensuring good usability on the existing platforms. I don't think I can prioritise more platforms at the moment.

Feel free to ask any more questions if you have any.
