### ISSUE TITLE
Too easy to ruin the UI using Papaya 

### ISSUE THREAD

**Issue by hugows** [ApoorvaJ/Papaya#24]
Maybe that UI PNG could be embedded in the .exe? Or use a different extension that Papaya doesn't open by default? :)

![Papaya no UI](https://cloud.githubusercontent.com/assets/11545/17809279/cb02c72c-65eb-11e6-93fc-71d60c64aa99.png)

**Comment by ApoorvaJ** [comment]
I think of this as a feature. This makes Papaya easily skinnable. If you do accidentally screw it up, you can always download a fresh version. I'm even thinking of taking this idea a step further and exposing all the GLSL shaders as editable text files.

Closing this bug, as I have a pretty strong opinion about keeping things simple and moddable wherever possible. Thanks for taking the time to try out Papaya and to write in with your suggestions, though. :)
