### ISSUE TITLE
Crash when clicking on icon with loaded image

### ISSUE THREAD

**Issue by nem0** [ApoorvaJ/Papaya#4]
Steps to reproduce: 
1. Load an image (I tried both jpeg and png, no difference)
2. click on the icon in the top left corner
3. observe crash

Note: it crashes in nvidia driver, so I guess it's some invalid opengl call
Note: HEAP[Papaya.exe]: Heap block at 048A47C8 modified at 048A4863 past requested size of 93, I printed all the allocations from Papaya, there are some close allocations
Note: It does not crash if there is no image or there had been an image and it has been closed.
Note: If I disable 

```
WindowFlags |= ImGuiWindowFlags_NoTitleBar;
WindowFlags |= ImGuiWindowFlags_NoResize;
```

for the icon, it does not crash

**Comment by ApoorvaJ** [comment]
Thanks for the detailed report.

I was able to reproduce the issue. In a quick test, the crash doesn't occur if I change the icon drawing line of code from

```
 ImGui::Image((void*)(intptr_t)Mem.Textures[PapayaTex_TitleBarIcon], ImVec2(28,28));
```

to

```
 ImGui::ImageButton((void*)(intptr_t)Mem.Textures[PapayaTex_TitleBarIcon], ImVec2(28,28));
```

This makes me think that it might be an issue with ImGui, or I that might be using ImGui::Image() incorrectly. I am looking into it, and will get back to you as soon as I find anything.

**Comment by ApoorvaJ** [comment]
The crash was a side-effect of me using an incorrect vertex buffer. The issue only manifested itself when a very specific set of conditions were true. Hence the strange behavior.

I have stopped the crash for now, and left a TODO note for myself to improve that part of the code even further.

**Comment by nem0** [comment]
Cool, it doesn ot crash anymore. 

btw 

```
const int32 FileNameSize = 400; // TODO: What's a good value for this?
```

[MAX_PATH](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx) is the answer :)

**Comment by ApoorvaJ** [comment]
Fixed. That was an interesting read. Thanks again. :)
