### ISSUE TITLE
Icons not loading under linux

### ISSUE THREAD

**Issue by superfunc** [ApoorvaJ/Papaya#7]
System Info:

```
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.0.2
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 11.0.2
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.0.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

ii  libxi-dev               2:1.7.4-1        amd64            X11 Input extension library (development headers)

ii  freeglut3:amd64         2.8.1-2          amd64            OpenGL Utility Toolkit

ii  libx11-dev:amd64        2:1.6.3-1ubuntu2 amd64            X11 client-side library (development headers)
```

Here is what papaya looks like when launched:

![papaya_bug](https://cloud.githubusercontent.com/assets/1583002/14101438/61e88f14-f549-11e5-8e3f-e838b275da61.png)

It expresses the following error in the console

```
OpenGL Error: Invalid value in ../../src/papaya_core.cpp:37
    --- Expression: glTexImage2D (GL_TEXTURE_2D, 0, GL_RGBA8, ImageWidth, ImageHeight, 0, GL_RGBA, GL_UNSIGNED_BYTE, Image)
```

**Comment by ApoorvaJ** [comment]
You currently have to manually copy the icons from the img/ folder to where your binary is being built (build/linux/). I will automate this in the makefile and then close the issue.

I'm kinda in the middle of moving from a single-translation-unit build to a makefile-based build, so things are a bit rough around the edges. Documentation regarding building is out of date too.

Thanks for taking the time and effort to report, though. :)

**Comment by superfunc** [comment]
No trouble! There seems to be a further issue, which is that the open file dialog brings up nothing.

**Comment by ApoorvaJ** [comment]
Also known. :) Haven't linked GTK in the makefile yet. I'll have it fixed by this weekend.

I suggest you try the release version, tagged v0.1. That should be a lot more stable than the current master branch.

**Comment by superfunc** [comment]
Right on, sorry for the extra noise then!

**Comment by ApoorvaJ** [comment]
Both problems should now be fixed. Closing the issue. 

Please let me know if you still have problems.
